[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "https://mldm.pachyderm.com/:splat"
  to = "https://hpe-ai-solutions-documentation.netlify.app/products/mldm/:splat"
  status = 301
  force = true
